# Generated by Django 6.1.1 on 2026-09-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('diagnose_misconception', 'Diagnose misconception'), ('analyse_decline', 'Analyse decline'), ('plan_week', 'Plan the week'), ('answer_forensics', 'Answer forensics'), ('generate_practice', 'Generate practice'), ('weekly_summary', 'Weekly summary')], max_length=32)),
                ('context', models.JSONField()),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=16)),
                ('output', models.JSONField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('human_verdict', models.CharField(choices=[('agreed', 'Mentor agreed'), ('disagreed', 'Mentor disagreed'), ('unreviewed', 'Not yet reviewed')], default='unreviewed', help_text='What turns a model guess into a training label.', max_length=12)),
                ('human_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.mentor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasoning_traces', to='tenancy.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'context_hash'], name='idx_trace_cache'), models.Index(fields=['institute', 'task', '-created_at'], name='idx_trace_recent'), models.Index(fields=['human_verdict'], name='idx_trace_verdict')],
            },
        ),
    ]
