# Generated by Django 6.1.1 on 2026-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasoning', '0002_reasoning_trace_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoningtrace',
            name='task',
            field=models.CharField(choices=[('diagnose_misconception', 'Diagnose misconception'), ('analyse_decline', 'Analyse decline'), ('plan_week', 'Plan the week'), ('answer_forensics', 'Answer forensics'), ('generate_practice', 'Generate practice'), ('weekly_summary', 'Weekly summary'), ('read_paper', 'Read an official paper'), ('solve_blind', 'Solve questions without the key'), ('tag_questions', 'Tag chapter, difficulty, distractors')], max_length=32),
        ),
    ]
