# Generated by Django 6.1.1 on 2026-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('blank', 'Skipped deliberately'), ('not_reached', 'Ran out of time')], max_length=12)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('marks', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('mock', 'Mock test'), ('practice', 'Practice')], default='mock', max_length=10)),
                ('ts', models.DateTimeField()),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taught_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'chapter statuses',
            },
        ),
        migrations.CreateModel(
            name='ConfidenceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.IntegerField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='RevisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
                ('scheduled_for', models.DateField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('mode', models.CharField(choices=[('learn', 'Learn'), ('practice', 'Practice'), ('revise', 'Revise')], max_length=10)),
                ('ts', models.DateTimeField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
