# Generated by Django 6.1.1 on 2026-09-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('ingestion', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('tenancy', '0002_institute_batch_mentor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='test_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='ingestion.testpaper'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='chapterstatus',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_statuses', to='tenancy.batch'),
        ),
        migrations.AddField(
            model_name='chapterstatus',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='chapterstatus',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_statuses', to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='confidencerating',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='confidencerating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_ratings', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='confidencerating',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confidence_ratings', to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='revisionevent',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='revisionevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_events', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='revisionevent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_events', to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_logs', to='syllabus.topic'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'topic', 'ts'], name='idx_attempt_stu_top_ts'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['institute', 'ts'], name='idx_attempt_inst_ts'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['test_paper'], name='idx_attempt_paper'),
        ),
        migrations.AddConstraint(
            model_name='chapterstatus',
            constraint=models.UniqueConstraint(fields=('batch', 'topic'), name='uniq_chapter_per_batch'),
        ),
        migrations.AddIndex(
            model_name='confidencerating',
            index=models.Index(fields=['student', 'topic', 'ts'], name='idx_conf_stu_top_ts'),
        ),
        migrations.AddIndex(
            model_name='revisionevent',
            index=models.Index(fields=['student', 'scheduled_for'], name='idx_rev_stu_sched'),
        ),
        migrations.AddIndex(
            model_name='studylog',
            index=models.Index(fields=['student', 'topic', 'ts'], name='idx_log_stu_top_ts'),
        ),
    ]
