# Generated by Django 6.1.1 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
        ('ingestion', '0002_initial'),
        ('syllabus', '0002_initial'),
        ('tenancy', '0003_row_level_security'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attempt',
            name='idx_attempt_paper',
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'test_paper'], name='idx_attempt_stu_paper'),
        ),
    ]
