# Generated by Django 6.1.1 on 2026-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attempt_index_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='chosen_option',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
