/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sets the `csrftoken` cookie. Call once before POSTing to login. */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Exchange credentials for a session cookie.
         *
         *     `authentication_classes` is empty on purpose: DRF's
         *     `SessionAuthentication` enforces CSRF on the *authenticated* path, and
         *     running it here would have it inspect a session that does not exist
         *     yet. Django's `CsrfViewMiddleware` still protects this POST.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description End the session. POST only — a GET logout is a CSRF vector. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["batches_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["batches_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The director's KPI strip. Three things were wrong with it.
         *
         *     **① It read the institute's entire attempt history.** The old
         *     `batch_mock_avg` query was `filter(test_paper__isnull=False)` with
         *     an `order_by` that the aggregate discarded, so Postgres did a Seq
         *     Scan over every attempt ever recorded — 24,000 rows and 343
         *     buffers on the seed, and O(history) on the most-visited page in
         *     the product. At the design's volume (45k attempts per institute
         *     per month) that is a multi-second query on every dashboard load.
         *
         *     No index fixes it, because the query genuinely wanted every row.
         *     Asking for one paper instead is what fixes it: the DB agent
         *     measured the rewritten form at **56 buffers and 0.687 ms, 12x
         *     faster**, and — the part that matters more than the multiple — it
         *     stops growing with history.
         *
         *     **② `batch_mock_avg` was a SUM.** It added up every mark scored by
         *     every student on every paper and presented the total as an
         *     average. On the seeded institute it read 8,437.0 out of a possible
         *     300. It is now the mean total per student on the latest paper.
         *
         *     **③ `revision_debt_pct` was not a percentage.** It divided a sum
         *     of per-student overdue counts by the student count — a mean, not a
         *     share, free to exceed 100 and meaningless against the `%` the UI
         *     renders beside it. It is now the share of scheduled revisions that
         *     are overdue, and the old quantity is still available under the
         *     name it should always have had, `avg_revision_debt`.
         */
        get: operations["dashboard_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["flags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["flags_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/{id}/intervene/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Log what the mentor did. This is what closes the risk loop. */
        post: operations["flags_intervene_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Who the caller is, and which institute they are bound to.
         *
         *     The console reads `role` to decide which navigation to render, and
         *     `institute` to label it. Both come from the same place the tenant
         *     middleware reads, so a UI that trusts this payload and a database that
         *     enforces RLS cannot disagree about who the caller is.
         */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/plan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Today's plan for the logged-in student. */
        get: operations["my_plan_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/plan/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Today's plan for the logged-in student. */
        post: operations["my_plan_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/study-logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["my_study_logs_list"];
        put?: never;
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        post: operations["my_study_logs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["papers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["papers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["students_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["students_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/attempts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["students_attempts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/marks-lost/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Partition lost marks by cause for one paper.
         *
         *     The attribution itself lives in
         *     `apps.events.services.mock_analysis` — it is an engine, not a
         *     view, and it is called by the planner and the narration layer too.
         */
        get: operations["students_marks_lost_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/mock-scores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Per-subject totals for every paper this student sat. */
        get: operations["students_mock_scores_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/subject-breakdown/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Study-time share vs marks-lost share. The neglect chart.
         *
         *     `marks_lost_share_pct` is now a share of **marks**, computed by
         *     `features.marks_lost_by_topic`. It previously counted lost
         *     *questions*, which priced a wrong answer and a skipped one
         *     identically despite the negative marking, and so understated
         *     exactly the subject a student was guessing through. Same field,
         *     same units claimed, finally the units delivered — and the same
         *     function the `subject_imbalance` detector reads, so the flag and
         *     this chart can no longer disagree.
         */
        get: operations["students_subject_breakdown_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/topic-states/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Restrict every queryset to the caller's institute.
         *
         *     Kept deliberately, alongside Postgres row-level security, and the DB
         *     agent's handoff argues the case at length. The short version is that
         *     RLS does not cover two cases this does:
         *
         *     * **Superusers bypass RLS entirely**, by design — the admin is
         *       cross-tenant back-office. Without this mixin a superuser's API call
         *       would quietly return every institute's students.
         *     * **RLS binding happens in middleware, off `request.user`.** Add JWT
         *       or token auth and DRF authenticates *inside* the view, by which
         *       point the middleware has already seen `AnonymousUser` and left the
         *       connection unscoped. This still works.
         *
         *     The two are not independent sources of truth: both derive the
         *     institute from the same user, and `manage.py rls_check` asserts the
         *     database half.
         */
        get: operations["students_topic_states_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attempt: {
            readonly id: number;
            question_id: string;
            readonly topic_name: string;
            status: components["schemas"]["StatusEnum"];
            time_spent?: number | null;
            /** Format: double */
            marks?: number;
            source?: components["schemas"]["SourceEnum"];
            /** Format: date-time */
            ts: string;
        };
        Batch: {
            readonly id: number;
            name: string;
            readonly exam_code: string;
            year: number;
            /** Format: date */
            exam_date?: string | null;
            readonly student_count: number;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `conceptual_gap` - conceptual_gap
         *     * `execution_error` - execution_error
         *     * `time_exhaustion` - time_exhaustion
         *     * `avoidable_skip` - avoidable_skip
         * @enum {string}
         */
        CauseEnum: "conceptual_gap" | "execution_error" | "time_exhaustion" | "avoidable_skip";
        /**
         * @description Director's KPI strip.
         *
         *     Two fields here changed *meaning* in v0.2 and the frontend must know:
         *
         *     `batch_mock_avg` was a SUM of every mark every student ever scored on
         *     every paper, labelled as an average. It is now the mean total per
         *     student on the latest paper — which is what the label always claimed,
         *     and is also 12x cheaper because it stops reading the institute's
         *     entire history on every dashboard load.
         *
         *     `revision_debt_pct` divided a sum of per-student debts by a student
         *     count and called the result a percentage; it could exceed 100 freely.
         *     It is now the genuine share of scheduled revisions that are overdue.
         *     The old quantity survives as `avg_revision_debt`, correctly named.
         */
        DashboardSummary: {
            total_students: number;
            active_students: number;
            flagged_this_week: number;
            critical_flags: number;
            /**
             * Format: double
             * @description Mean total marks per student on the most recent paper.
             */
            batch_mock_avg: number | null;
            latest_paper_id: number | null;
            latest_paper_name: string | null;
            /** Format: date */
            latest_paper_held_on: string | null;
            latest_paper_max_marks: number | null;
            /** @description How many students sat the paper `batch_mock_avg` is computed over. */
            latest_paper_students: number;
            /**
             * Format: double
             * @description Share of scheduled revisions now past due and not done.
             */
            revision_debt_pct: number;
            /**
             * Format: double
             * @description Mean overdue revision cycles per student.
             */
            avg_revision_debt: number;
            flags_resolved: number;
            /**
             * Format: double
             * @description Share of closed flags whose outcome was 'recovered'.
             */
            recovery_rate_pct: number | null;
        };
        /** @description The one-key error/ack envelope DRF already uses everywhere. */
        Detail: {
            detail: string;
        };
        Flag: {
            readonly id: number;
            readonly student_id: number;
            readonly student_name: string;
            readonly batch_name: string;
            readonly mentor_name: string;
            readonly topic_name: string;
            type: string;
            severity: components["schemas"]["SeverityEnum"];
            headline: string;
            evidence?: unknown;
            rule_version?: string;
            /** Format: date-time */
            raised_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
            outcome?: components["schemas"]["OutcomeEnum"] | components["schemas"]["BlankEnum"];
            readonly is_open: boolean;
        };
        Institute: {
            readonly id: number;
            name: string;
            city: string;
            slug: string;
        };
        Intervention: {
            readonly id: number;
            flag: number;
            mentor: number;
            readonly mentor_name: string;
            action: string;
            /** Format: date-time */
            readonly taken_at: string;
        };
        InterventionRequest: {
            flag: number;
            mentor: number;
            action: string;
        };
        /**
         * @description * `subject` - Subject
         *     * `unit` - Unit
         *     * `chapter` - Chapter
         * @enum {string}
         */
        KindEnum: "subject" | "unit" | "chapter";
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @description Where the marks actually went, by chapter. */
        LossTopic: {
            topic_id: number | null;
            topic: string;
            subject: string;
            /** Format: double */
            marks_lost: number;
            questions: number;
        };
        /**
         * @description Mistake taxonomy for one paper — the line that sells the product.
         *
         *     The four cause fields and `total_lost` / `recoverable` are unchanged
         *     from v0.1. Everything else is additive: paper identity, the score the
         *     taxonomy partitions, the student's own pace baseline that the cause
         *     rules used, and the per-chapter breakdown a mentor asks for next.
         */
        MarksLost: {
            paper_id: number;
            paper_name: string;
            /** Format: date */
            held_on: string;
            max_marks: number;
            questions: number;
            attempted: number;
            /** Format: double */
            score: number;
            conceptual_gap: number;
            execution_error: number;
            time_exhaustion: number;
            avoidable_skip: number;
            total_lost: number;
            /** @description Marks lost to causes that need no new learning. */
            recoverable: number;
            /**
             * Format: double
             * @description Median seconds this student spends on a question they get right. Null when they have fewer than 8 timed correct answers, in which case the time rule was not applied.
             */
            time_baseline_sec: number | null;
            causes: components["schemas"]["MarksLostCause"][];
            top_loss_topics: components["schemas"]["LossTopic"][];
        };
        /** @description One row of the mistake taxonomy, chart-ready. */
        MarksLostCause: {
            cause: components["schemas"]["CauseEnum"];
            marks: number;
            questions: number;
            /** Format: double */
            share_pct: number;
        };
        /** @description The caller's identity. Drives navigation and the institute label. */
        Me: {
            id: number;
            username: string;
            name: string;
            email: string;
            /**
             * @description Null for an authenticated account attached to nothing — which sees no tenant data at all, by design.
             *
             *     * `mentor` - mentor
             *     * `student` - student
             *     * `director` - director
             */
            role: (components["schemas"]["RoleEnum"] | components["schemas"]["NullEnum"]) | null;
            institute: components["schemas"]["Institute"] | null;
            mentor_id: number | null;
            student_id: number | null;
            is_staff: boolean;
            is_superuser: boolean;
        };
        Mentor: {
            readonly id: number;
            name: string;
            email?: string;
        };
        MockScore: {
            paper_id: number;
            paper_name: string;
            /** Format: date */
            held_on: string;
            /** Format: double */
            physics: number;
            /** Format: double */
            chemistry: number;
            /** Format: double */
            maths: number;
            /** Format: double */
            total: number;
        };
        /**
         * @description * `learn` - Learn
         *     * `practice` - Practice
         *     * `revise` - Revise
         * @enum {string}
         */
        ModeEnum: "learn" | "practice" | "revise";
        /** @enum {unknown} */
        NullEnum: null;
        /**
         * @description * `recovered` - Recovered
         *     * `declined` - Declined
         *     * `unknown` - Unknown
         * @enum {string}
         */
        OutcomeEnum: "recovered" | "declined" | "unknown";
        PaginatedAttemptList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Attempt"][];
        };
        PaginatedBatchList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Batch"][];
        };
        PaginatedFlagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Flag"][];
        };
        PaginatedMockScoreList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MockScore"][];
        };
        PaginatedPlanBlockList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PlanBlock"][];
        };
        PaginatedStudentListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudentList"][];
        };
        PaginatedStudyLogCreateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudyLogCreate"][];
        };
        PaginatedSubjectBreakdownList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubjectBreakdown"][];
        };
        PaginatedTestPaperList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TestPaper"][];
        };
        PaginatedTopicStateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TopicState"][];
        };
        PlanBlock: {
            readonly id: number;
            /** Format: date */
            readonly date: string;
            /** Format: time */
            readonly start_time: string | null;
            readonly minutes: number;
            readonly mode: string;
            readonly topic_name: string;
            readonly subject: string;
            readonly reason_code: string;
            reason_text?: string;
            completed?: boolean;
        };
        /**
         * @description * `mentor` - mentor
         *     * `student` - student
         *     * `director` - director
         * @enum {string}
         */
        RoleEnum: "mentor" | "student" | "director";
        /**
         * @description * `watch` - Watch
         *     * `high` - High
         *     * `critical` - Critical
         *     * `improving` - Improving
         * @enum {string}
         */
        SeverityEnum: "watch" | "high" | "critical" | "improving";
        /**
         * @description * `mock` - Mock test
         *     * `practice` - Practice
         * @enum {string}
         */
        SourceEnum: "mock" | "practice";
        /**
         * @description * `correct` - Correct
         *     * `wrong` - Wrong
         *     * `blank` - Skipped deliberately
         *     * `not_reached` - Ran out of time
         * @enum {string}
         */
        StatusEnum: "correct" | "wrong" | "blank" | "not_reached";
        StudentDetail: {
            readonly id: number;
            name: string;
            roll_no: string;
            target?: string;
            /** Format: date */
            joined_at: string;
            /** Format: date */
            exited_at?: string | null;
            readonly batch: components["schemas"]["Batch"];
            readonly mentor: components["schemas"]["Mentor"];
            readonly state: components["schemas"]["StudentState"];
        };
        /** @description Row in the director's triage table. */
        StudentList: {
            readonly id: number;
            name: string;
            roll_no: string;
            readonly batch_name: string;
            readonly mentor_name: string;
            target?: string;
            /** Format: double */
            readonly risk_score: number;
            /** Format: double */
            readonly mock_trend: number;
            /** Format: double */
            readonly mock_avg: number;
            readonly open_flags: number;
            /** Format: date */
            exited_at?: string | null;
        };
        StudentState: {
            /** Format: double */
            consistency?: number | null;
            /** Format: double */
            load_index?: number | null;
            /** Format: double */
            balance_index?: number | null;
            revision_debt?: number;
            /** Format: double */
            risk_score?: number | null;
            /** Format: double */
            mock_avg?: number | null;
            /** Format: double */
            mock_trend?: number | null;
            /** Format: double */
            syllabus_pct?: number | null;
            /** Format: date-time */
            readonly computed_at: string;
        };
        StudyLogCreate: {
            readonly id: number;
            topic: number;
            minutes: number;
            mode: components["schemas"]["ModeEnum"];
            /** Format: date-time */
            ts: string;
        };
        StudyLogCreateRequest: {
            topic: number;
            minutes: number;
            mode: components["schemas"]["ModeEnum"];
            /** Format: date-time */
            ts: string;
        };
        /** @description Time share vs marks-lost share — the neglect chart. */
        SubjectBreakdown: {
            subject: string;
            /** Format: double */
            time_share_pct: number;
            /** Format: double */
            marks_lost_share_pct: number;
            /** Format: double */
            accuracy_pct: number | null;
        };
        TestPaper: {
            readonly id: number;
            name: string;
            /** Format: date */
            held_on: string;
            total_questions?: number;
            max_marks?: number;
            duration_min?: number;
        };
        Topic: {
            readonly id: number;
            name: string;
            kind: components["schemas"]["KindEnum"];
            /** Format: double */
            weight?: number;
            readonly subject: string;
        };
        TopicState: {
            readonly id: number;
            readonly topic: components["schemas"]["Topic"];
            /** Format: double */
            mastery?: number | null;
            /** Format: double */
            retention?: number | null;
            attempts_n?: number;
            correct_n?: number;
            /** Format: double */
            accuracy_30d?: number | null;
            exposure_min?: number;
            /** Format: double */
            avg_time_spent?: number | null;
            self_rating?: number | null;
            /** Format: double */
            readonly confidence_gap: number;
            /** Format: date-time */
            last_seen?: string | null;
            /** Format: date-time */
            last_revised?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batches_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBatchList"];
                };
            };
        };
    };
    batches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    dashboard_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    flags_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFlagList"];
                };
            };
        };
    };
    flags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this flag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flag"];
                };
            };
        };
    };
    flags_intervene_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this flag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InterventionRequest"];
                "multipart/form-data": components["schemas"]["InterventionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    my_plan_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlanBlockList"];
                };
            };
        };
    };
    my_plan_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan block. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanBlock"];
                };
            };
        };
    };
    my_study_logs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudyLogCreateList"];
                };
            };
        };
    };
    my_study_logs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyLogCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyLogCreateRequest"];
                "multipart/form-data": components["schemas"]["StudyLogCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyLogCreate"];
                };
            };
        };
    };
    papers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTestPaperList"];
                };
            };
        };
    };
    papers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this test paper. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPaper"];
                };
            };
        };
    };
    students_list: {
        parameters: {
            query?: {
                active?: boolean;
                at_risk?: boolean;
                batch?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudentListList"];
                };
            };
        };
    };
    students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
        };
    };
    students_attempts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttemptList"];
                };
            };
        };
    };
    students_marks_lost_retrieve: {
        parameters: {
            query: {
                /** @description Include the per-question cause breakdown. */
                detail?: boolean;
                paper: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarksLost"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    students_mock_scores_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMockScoreList"];
                };
            };
        };
    };
    students_subject_breakdown_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectBreakdownList"];
                };
            };
        };
    };
    students_topic_states_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTopicStateList"];
                };
            };
        };
    };
}
