/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["batches_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["batches_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["dashboard_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["flags_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["flags_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/{id}/intervene/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Log what the mentor did. This is what closes the risk loop. */
        post: operations["flags_intervene_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/plan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Today's plan for the logged-in student. */
        get: operations["my_plan_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/plan/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Today's plan for the logged-in student. */
        post: operations["my_plan_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/my/study-logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["my_study_logs_list"];
        put?: never;
        /** @description Restrict every queryset to the caller's institute. */
        post: operations["my_study_logs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["papers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["papers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["students_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["students_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/attempts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["students_attempts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/marks-lost/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Partition lost marks by cause for one paper.
         *
         *     Cause is inferred from status plus prior mastery on the topic:
         *     a wrong answer on a topic the student knows is an execution error,
         *     not a conceptual gap.
         */
        get: operations["students_marks_lost_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/mock-scores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Per-subject totals for every paper this student sat. */
        get: operations["students_mock_scores_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/subject-breakdown/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Study-time share vs marks-lost share. The neglect chart. */
        get: operations["students_subject_breakdown_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/topic-states/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Restrict every queryset to the caller's institute. */
        get: operations["students_topic_states_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attempt: {
            readonly id: number;
            question_id: string;
            readonly topic_name: string;
            status: components["schemas"]["StatusEnum"];
            time_spent?: number | null;
            /** Format: double */
            marks?: number;
            source?: components["schemas"]["SourceEnum"];
            /** Format: date-time */
            ts: string;
        };
        Batch: {
            readonly id: number;
            name: string;
            readonly exam_code: string;
            year: number;
            /** Format: date */
            exam_date?: string | null;
            readonly student_count: number;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description Director's KPI strip. */
        DashboardSummary: {
            total_students: number;
            active_students: number;
            flagged_this_week: number;
            critical_flags: number;
            /** Format: double */
            batch_mock_avg: number | null;
            /** Format: double */
            revision_debt_pct: number;
            flags_resolved: number;
            /**
             * Format: double
             * @description Share of closed flags whose outcome was 'recovered'.
             */
            recovery_rate_pct: number | null;
        };
        Flag: {
            readonly id: number;
            readonly student_id: number;
            readonly student_name: string;
            readonly batch_name: string;
            readonly mentor_name: string;
            readonly topic_name: string;
            type: string;
            severity: components["schemas"]["SeverityEnum"];
            headline: string;
            evidence?: unknown;
            rule_version?: string;
            /** Format: date-time */
            raised_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
            outcome?: components["schemas"]["OutcomeEnum"] | components["schemas"]["BlankEnum"];
            readonly is_open: boolean;
        };
        Intervention: {
            readonly id: number;
            flag: number;
            mentor: number;
            readonly mentor_name: string;
            action: string;
            /** Format: date-time */
            readonly taken_at: string;
        };
        InterventionRequest: {
            flag: number;
            mentor: number;
            action: string;
        };
        /**
         * @description * `subject` - Subject
         *     * `unit` - Unit
         *     * `chapter` - Chapter
         * @enum {string}
         */
        KindEnum: "subject" | "unit" | "chapter";
        /** @description Mistake taxonomy for one paper — the line that sells the product. */
        MarksLost: {
            conceptual_gap: number;
            execution_error: number;
            time_exhaustion: number;
            avoidable_skip: number;
            total_lost: number;
            /** @description Marks lost to causes that need no new learning. */
            recoverable: number;
        };
        Mentor: {
            readonly id: number;
            name: string;
            email?: string;
        };
        MockScore: {
            paper_id: number;
            paper_name: string;
            /** Format: date */
            held_on: string;
            /** Format: double */
            physics: number;
            /** Format: double */
            chemistry: number;
            /** Format: double */
            maths: number;
            /** Format: double */
            total: number;
        };
        /**
         * @description * `learn` - Learn
         *     * `practice` - Practice
         *     * `revise` - Revise
         * @enum {string}
         */
        ModeEnum: "learn" | "practice" | "revise";
        /**
         * @description * `recovered` - Recovered
         *     * `declined` - Declined
         *     * `unknown` - Unknown
         * @enum {string}
         */
        OutcomeEnum: "recovered" | "declined" | "unknown";
        PaginatedAttemptList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Attempt"][];
        };
        PaginatedBatchList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Batch"][];
        };
        PaginatedFlagList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Flag"][];
        };
        PaginatedMockScoreList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MockScore"][];
        };
        PaginatedPlanBlockList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PlanBlock"][];
        };
        PaginatedStudentListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudentList"][];
        };
        PaginatedStudyLogCreateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudyLogCreate"][];
        };
        PaginatedSubjectBreakdownList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubjectBreakdown"][];
        };
        PaginatedTestPaperList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TestPaper"][];
        };
        PaginatedTopicStateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TopicState"][];
        };
        PlanBlock: {
            readonly id: number;
            /** Format: date */
            readonly date: string;
            /** Format: time */
            readonly start_time: string | null;
            readonly minutes: number;
            readonly mode: string;
            readonly topic_name: string;
            readonly subject: string;
            readonly reason_code: string;
            reason_text?: string;
            completed?: boolean;
        };
        /**
         * @description * `watch` - Watch
         *     * `high` - High
         *     * `critical` - Critical
         *     * `improving` - Improving
         * @enum {string}
         */
        SeverityEnum: "watch" | "high" | "critical" | "improving";
        /**
         * @description * `mock` - Mock test
         *     * `practice` - Practice
         * @enum {string}
         */
        SourceEnum: "mock" | "practice";
        /**
         * @description * `correct` - Correct
         *     * `wrong` - Wrong
         *     * `blank` - Skipped deliberately
         *     * `not_reached` - Ran out of time
         * @enum {string}
         */
        StatusEnum: "correct" | "wrong" | "blank" | "not_reached";
        StudentDetail: {
            readonly id: number;
            name: string;
            roll_no: string;
            target?: string;
            /** Format: date */
            joined_at: string;
            /** Format: date */
            exited_at?: string | null;
            readonly batch: components["schemas"]["Batch"];
            readonly mentor: components["schemas"]["Mentor"];
            readonly state: components["schemas"]["StudentState"];
        };
        /** @description Row in the director's triage table. */
        StudentList: {
            readonly id: number;
            name: string;
            roll_no: string;
            readonly batch_name: string;
            readonly mentor_name: string;
            target?: string;
            /** Format: double */
            readonly risk_score: number;
            /** Format: double */
            readonly mock_trend: number;
            /** Format: double */
            readonly mock_avg: number;
            readonly open_flags: number;
            /** Format: date */
            exited_at?: string | null;
        };
        StudentState: {
            /** Format: double */
            consistency?: number | null;
            /** Format: double */
            load_index?: number | null;
            /** Format: double */
            balance_index?: number | null;
            revision_debt?: number;
            /** Format: double */
            risk_score?: number | null;
            /** Format: double */
            mock_avg?: number | null;
            /** Format: double */
            mock_trend?: number | null;
            /** Format: double */
            syllabus_pct?: number | null;
            /** Format: date-time */
            readonly computed_at: string;
        };
        StudyLogCreate: {
            readonly id: number;
            topic: number;
            minutes: number;
            mode: components["schemas"]["ModeEnum"];
            /** Format: date-time */
            ts: string;
        };
        StudyLogCreateRequest: {
            topic: number;
            minutes: number;
            mode: components["schemas"]["ModeEnum"];
            /** Format: date-time */
            ts: string;
        };
        /** @description Time share vs marks-lost share — the neglect chart. */
        SubjectBreakdown: {
            subject: string;
            /** Format: double */
            time_share_pct: number;
            /** Format: double */
            marks_lost_share_pct: number;
            /** Format: double */
            accuracy_pct: number | null;
        };
        TestPaper: {
            readonly id: number;
            name: string;
            /** Format: date */
            held_on: string;
            total_questions?: number;
            max_marks?: number;
            duration_min?: number;
        };
        Topic: {
            readonly id: number;
            name: string;
            kind: components["schemas"]["KindEnum"];
            /** Format: double */
            weight?: number;
            readonly subject: string;
        };
        TopicState: {
            readonly id: number;
            readonly topic: components["schemas"]["Topic"];
            /** Format: double */
            mastery?: number | null;
            /** Format: double */
            retention?: number | null;
            attempts_n?: number;
            correct_n?: number;
            /** Format: double */
            accuracy_30d?: number | null;
            exposure_min?: number;
            /** Format: double */
            avg_time_spent?: number | null;
            self_rating?: number | null;
            /** Format: double */
            readonly confidence_gap: number;
            /** Format: date-time */
            last_seen?: string | null;
            /** Format: date-time */
            last_revised?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    batches_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBatchList"];
                };
            };
        };
    };
    batches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this batch. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
        };
    };
    dashboard_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    flags_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFlagList"];
                };
            };
        };
    };
    flags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this flag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flag"];
                };
            };
        };
    };
    flags_intervene_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this flag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InterventionRequest"];
                "multipart/form-data": components["schemas"]["InterventionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"];
                };
            };
        };
    };
    my_plan_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlanBlockList"];
                };
            };
        };
    };
    my_plan_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this plan block. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanBlock"];
                };
            };
        };
    };
    my_study_logs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudyLogCreateList"];
                };
            };
        };
    };
    my_study_logs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyLogCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyLogCreateRequest"];
                "multipart/form-data": components["schemas"]["StudyLogCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyLogCreate"];
                };
            };
        };
    };
    papers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTestPaperList"];
                };
            };
        };
    };
    papers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this test paper. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPaper"];
                };
            };
        };
    };
    students_list: {
        parameters: {
            query?: {
                active?: boolean;
                at_risk?: boolean;
                batch?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudentListList"];
                };
            };
        };
    };
    students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
        };
    };
    students_attempts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAttemptList"];
                };
            };
        };
    };
    students_marks_lost_retrieve: {
        parameters: {
            query: {
                paper: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarksLost"];
                };
            };
        };
    };
    students_mock_scores_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMockScoreList"];
                };
            };
        };
    };
    students_subject_breakdown_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubjectBreakdownList"];
                };
            };
        };
    };
    students_topic_states_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTopicStateList"];
                };
            };
        };
    };
}
