# Generated by Django 6.1.1 on 2026-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('high', 'High'), ('critical', 'Critical'), ('improving', 'Improving')], max_length=10)),
                ('headline', models.CharField(max_length=300)),
                ('evidence', models.JSONField(default=dict)),
                ('rule_version', models.CharField(default='v1', max_length=20)),
                ('raised_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('declined', 'Declined'), ('unknown', 'Unknown')], max_length=12)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('taken_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('minutes', models.IntegerField()),
                ('mode', models.CharField(max_length=10)),
                ('reason_code', models.CharField(max_length=40)),
                ('reason_text', models.CharField(blank=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.FloatField(blank=True, null=True)),
                ('load_index', models.FloatField(blank=True, null=True)),
                ('balance_index', models.FloatField(blank=True, null=True)),
                ('revision_debt', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('mock_avg', models.FloatField(blank=True, null=True)),
                ('mock_trend', models.FloatField(blank=True, null=True)),
                ('syllabus_pct', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.FloatField(blank=True, null=True)),
                ('retention', models.FloatField(blank=True, null=True)),
                ('attempts_n', models.IntegerField(default=0)),
                ('correct_n', models.IntegerField(default=0)),
                ('accuracy_30d', models.FloatField(blank=True, null=True)),
                ('exposure_min', models.IntegerField(default=0)),
                ('avg_time_spent', models.FloatField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_revised', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
