# Generated by Django 6.1.1 on 2026-09-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('derived', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('tenancy', '0002_institute_batch_mentor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='flag',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='flag',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='derived.flag'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.mentor'),
        ),
        migrations.AddField(
            model_name='planblock',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='planblock',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_blocks', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='planblock',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='studentstate',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='studentstate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='topicstate',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='topicstate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_states', to='tenancy.student'),
        ),
        migrations.AddField(
            model_name='topicstate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_states', to='syllabus.topic'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['institute', 'resolved_at', 'severity'], name='idx_flag_triage'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['student', 'type'], name='idx_flag_stu_type'),
        ),
        migrations.AddIndex(
            model_name='planblock',
            index=models.Index(fields=['student', 'date'], name='idx_plan_stu_date'),
        ),
        migrations.AddIndex(
            model_name='studentstate',
            index=models.Index(fields=['institute', 'risk_score'], name='idx_sstate_inst_risk'),
        ),
        migrations.AddIndex(
            model_name='topicstate',
            index=models.Index(fields=['institute', 'mastery'], name='idx_tstate_inst_mastery'),
        ),
        migrations.AddIndex(
            model_name='topicstate',
            index=models.Index(fields=['student', 'mastery'], name='idx_tstate_stu_mastery'),
        ),
        migrations.AddConstraint(
            model_name='topicstate',
            constraint=models.UniqueConstraint(fields=('student', 'topic'), name='uniq_topic_state'),
        ),
    ]
