# Generated by Django 6.1.1 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derived', '0002_initial'),
        ('syllabus', '0002_initial'),
        ('tenancy', '0003_row_level_security'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(condition=models.Q(('resolved_at__isnull', True)), fields=['institute', 'severity', '-raised_at'], name='idx_flag_open'),
        ),
    ]
