# Generated by Django 6.1.1 on 2026-09-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('marks_correct', models.IntegerField(default=4)),
                ('marks_wrong', models.IntegerField(default=-1)),
                ('total_marks', models.IntegerField(default=300)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('subject', 'Subject'), ('unit', 'Unit'), ('chapter', 'Chapter')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['syllabus', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='syllabus.exam')),
            ],
            options={
                'ordering': ['institute', 'exam', '-version'],
            },
        ),
    ]
