# Generated by Django 6.1.1 on 2026-09-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        ('tenancy', '0002_institute_batch_mentor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusversion',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_versions', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.syllabusversion'),
        ),
        migrations.AddConstraint(
            model_name='syllabusversion',
            constraint=models.UniqueConstraint(fields=('institute', 'exam', 'version'), name='uniq_syllabus_version'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['syllabus', 'parent'], name='syllabus_to_syllabu_aacdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['syllabus', 'kind'], name='syllabus_to_syllabu_a279d9_idx'),
        ),
    ]
