# Generated by Django 6.1.1 on 2026-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ncert_ref',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
