# Generated by Django 6.1.1 on 2026-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('rows_ok', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('raw_snapshot', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ingest batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTopicMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('question_text', models.TextField(blank=True)),
                ('proposed_by', models.CharField(blank=True, choices=[('blueprint', 'Paper blueprint'), ('llm', 'LLM proposed'), ('manual', 'Manual')], max_length=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['test_paper', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('held_on', models.DateField()),
                ('total_questions', models.IntegerField(default=75)),
                ('max_marks', models.IntegerField(default=300)),
                ('marks_correct', models.IntegerField(default=4)),
                ('marks_wrong', models.IntegerField(default=-1)),
                ('duration_min', models.IntegerField(default=180)),
            ],
            options={
                'ordering': ['-held_on'],
            },
        ),
    ]
