# Generated by Django 6.1.1 on 2026-09-20 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('tenancy', '0002_institute_batch_mentor_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmappingprofile',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='ingestbatch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syllabus.exam'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.institute'),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_map', to='ingestion.testpaper'),
        ),
        migrations.AddField(
            model_name='ingestbatch',
            name='test_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.testpaper'),
        ),
        migrations.AddIndex(
            model_name='questiontopicmap',
            index=models.Index(fields=['test_paper', 'topic'], name='ingestion_q_test_pa_443a79_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontopicmap',
            constraint=models.UniqueConstraint(fields=('test_paper', 'question_id'), name='uniq_question_per_paper'),
        ),
        migrations.AddConstraint(
            model_name='ingestbatch',
            constraint=models.UniqueConstraint(fields=('institute', 'file_hash'), name='uniq_file_per_institute'),
        ),
    ]
