# Generated by Django 6.1.1 on 2026-09-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('subject', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='The wrong belief, stated as the student would hold it.')),
                ('remedy', models.TextField(blank=True, help_text='What actually fixes it. Shown to the mentor.')),
            ],
            options={
                'ordering': ['subject', 'code'],
            },
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=8),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='solution',
            field=models.TextField(blank=True, help_text='The worked method, not just the final answer.'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('misconception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distractors', to='ingestion.misconception')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ingestion.questiontopicmap')),
            ],
            options={
                'ordering': ['question', 'label'],
                'constraints': [models.UniqueConstraint(fields=('question', 'label'), name='uniq_option_per_question')],
            },
        ),
    ]
