# Generated by Django 6.1.1 on 2026-10-07 17:45
"""Provenance on every paper and question, for the question factory.

Additive only. Every existing row comes out `source='demo'` through the
field default — which is the truth: the diagnostic bank was written by us
and Mocks 8-14 are synthetic labels. Nothing existing changes meaning.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_misconception_questiontopicmap_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='draft_misconception',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='draft_misconception_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='answer_type',
            field=models.CharField(choices=[('mcq', 'Multiple choice'), ('numerical', 'Numerical value')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='has_diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='model_answer',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='nta_question_id',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='numeric_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='official_answer',
            field=models.CharField(blank=True, help_text="Exactly as the official key gives it, after mapping to this paper's labels: '2', '1,2' (both accepted), '225'.", max_length=32),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='source',
            field=models.CharField(choices=[('official_pyq', 'Official past paper'), ('demo', 'Demo (written by us)'), ('generated', 'Generated')], default='demo', max_length=16),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='source_ref',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='subject_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='verification',
            field=models.CharField(blank=True, choices=[('', 'Not cross-checked'), ('agreed', 'Model agreed with the official key'), ('disagreed', 'Model disagreed — needs a person'), ('unverifiable', 'Could not be checked (e.g. unreadable figure)')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='questiontopicmap',
            name='verification_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='shift_or_booklet',
            field=models.CharField(blank=True, help_text="NEET test-booklet code or JEE Main date and shift — the official key is per booklet / per shift, so this is part of the paper's identity, not a label.", max_length=80),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='source',
            field=models.CharField(choices=[('official_pyq', 'Official past paper'), ('demo', 'Demo (written by us)'), ('generated', 'Generated')], default='demo', max_length=16),
        ),
    ]
